name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Lint and test
      run: |
        yarn lint
        yarn test

    - name: Build app & storybook
      run: |
        yarn build
        mkdir -p "./dist/storybook/${{ github.head_ref }}"
        yarn build-storybook -o "./dist/storybook/${{ github.head_ref }}"

    - name: Prepare upload artifact - "${{ github.head_ref }}"
      run: |
        mkdir -p "./dist/__regressions__${{ github.head_ref }}/actual"
        yarn screenshot -o "./dist/__regressions__${{ github.head_ref }}/actual"
      if: contains(github.ref, 'master') == false

    - name: Upload artifact
    - uses: actions/upload-artifact@master
      with:
        name: screenshots
        path: "./dist/__regressions__/${{ github.head_ref }}/actual"
      if: contains(github.ref, 'master') == false

    - name: Deploy master
      run: |
        echo "./dist"
        ls ./dist
        echo "./dist/storybook/${{ github.head_ref }}"
      if: contains(github.ref, 'master')
